node_bot:
  chat_id: "your_chat_id_here"
  bot_token: "your_bot_token_here"

camera:
  stream_url: "your_stream_url_here"

# Optional HomeAssistant webhook integration
#homeassistant_webhook:
#  prey_detected_webhook: "your_webhook_url_here"
#  no_prey_detected_webhook: "your_webhook_url_here"